###########################################################################
# XMPP Site Configuration

title: "mattrude.com Communication Service"
description: ""
url: "https://im.mattrude.com"
name: "mattrude.com"
baseurl: "im.mattrude.com"
destination: "/var/www/im.mattrude.com"

owner-name: "Matt Rude"
owner-pgpkey: "0xc4909ee495b0761f"
owner-url: "https://mattrude.com/"
owner-xmpp: "matt@mattrude.com"
#owner-email: "matt@mattrude.com"
owner-twitter: "mdrude"
owner-github: "mattrude"

xmpp-url: "mattrude.com" # The XMPP domain url
xmpp-host: "im.mattrude.com" # The hostname of the server
xmpp-conference-url: "conference.mattrude.com" # Multi-User Chat xep-0045
xmpp-proxy-url: "proxy.mattrude.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)
xmpp-upload-url: "upload.mattrude.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)

server-features: 1
user-guide: 0

###########################################################################
# The below values should auto update

ejabberd-version: "18.09.7"
ejabberd-gitversion: "d8f831de096e6a4fc49d913e99035ef41869e0f7"
ejabberd-upload-days: "1825"
ejabberd-upload-fsize: "1 GB"

fingerprints: 1
fingerprint-expires: "Nov 17 05:00:12 2018 GMT"
fingerprint-im-expires: "Nov 21 22:58:32 2018 GMT"
fingerprint-conference-expires: "Nov 21 22:58:32 2018 GMT"
fingerprint-proxy-expires: "Nov 21 22:58:32 2018 GMT"
fingerprint-upload-expires: "Nov 21 22:58:32 2018 GMT"
fingerprint-sha1: "8B:7E:30:6F:8A:9A:90:BC:54:19:5F:19:C4:52:53:5C:3B:BA:F2:7B"
fingerprint-sha256: "E5:DC:0F:4C:33:57:AD:9B:A8:23:DD:8A:CB:28:05:FC:26:0D:1B:03:07:90:80:7E:51:C0:F1:26:30:FE:46:A2"
fingerprint-im-sha1: "A0:51:29:C8:7B:51:09:95:DC:80:49:E2:BD:F7:4F:7B:AC:C4:45:45"
fingerprint-im-sha256: "61:07:05:E2:DE:89:C0:C6:CA:DA:13:DE:A7:A4:71:7E:40:71:17:B3:C9:0B:C7:75:66:42:39:DE:B1:05:FB:60"
fingerprint-conference-sha1: "A0:51:29:C8:7B:51:09:95:DC:80:49:E2:BD:F7:4F:7B:AC:C4:45:45"
fingerprint-conference-sha256: "61:07:05:E2:DE:89:C0:C6:CA:DA:13:DE:A7:A4:71:7E:40:71:17:B3:C9:0B:C7:75:66:42:39:DE:B1:05:FB:60"
fingerprint-proxy-sha1: "A0:51:29:C8:7B:51:09:95:DC:80:49:E2:BD:F7:4F:7B:AC:C4:45:45"
fingerprint-proxy-sha256: "61:07:05:E2:DE:89:C0:C6:CA:DA:13:DE:A7:A4:71:7E:40:71:17:B3:C9:0B:C7:75:66:42:39:DE:B1:05:FB:60"
fingerprint-upload-sha1: "A0:51:29:C8:7B:51:09:95:DC:80:49:E2:BD:F7:4F:7B:AC:C4:45:45"
fingerprint-upload-sha256: "61:07:05:E2:DE:89:C0:C6:CA:DA:13:DE:A7:A4:71:7E:40:71:17:B3:C9:0B:C7:75:66:42:39:DE:B1:05:FB:60"

xep-0045: 1
xep-0065: 1
xep-0115: 1
xep-0160: 1
xep-0163: 1
xep-0191: 1
xep-0198: 1
xep-0280: 1
xep-0313: 1
xep-0352: 1
xep-0357: 1
xep-0363: 1
xep-0368: 1
xep-0384: 1
xep-0398: 1

# Analytics settings
#google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

include:
- .well-known/host-meta

exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
- css/syntax.less
- css/site.less
- css/small.less

plugins:
- jekyll-sitemap
  #- jekyll-press

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
