###########################################################################
# XMPP Site Configuration

title: "mattrude.com Communication Service"
description: ""
url: "https://im.mattrude.com"
name: "mattrude.com"
baseurl: "im.mattrude.com"
destination: "/var/www/im.mattrude.com"

owner-name: "Matt Rude"
owner-pgpkey: "0xc4909ee495b0761f"
owner-url: "https://mattrude.com/"
owner-xmpp: "matt@mattrude.com"
#owner-email: "matt@mattrude.com"
owner-twitter: "mdrude"
owner-github: "mattrude"

xmpp-url: "mattrude.com" # The XMPP domain url
xmpp-host: "im.mattrude.com" # The hostname of the server
xmpp-conference-url: "conference.mattrude.com" # Multi-User Chat xep-0045
xmpp-proxy-url: "proxy.mattrude.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)
xmpp-upload-url: "upload.mattrude.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)

server-features: 1
user-guide: 0

###########################################################################
# The below values should auto update

ejabberd-version: "18.06.109"
ejabberd-gitversion: "0cbd41fbdc6a9a3d2d3153fd9305c90538b0448a"
ejabberd-upload-days: "90"
ejabberd-upload-fsize: "1 GB"

fingerprints: 1
fingerprint-expires: "Nov 17 05:00:12 2018 GMT"
fingerprint-im-expires: "Nov 18 06:28:11 2018 GMT"
fingerprint-conference-expires: "Nov 18 06:28:11 2018 GMT"
fingerprint-proxy-expires: "Nov 18 06:28:11 2018 GMT"
fingerprint-upload-expires: "Nov 18 06:28:11 2018 GMT"
fingerprint-sha1: "8B:7E:30:6F:8A:9A:90:BC:54:19:5F:19:C4:52:53:5C:3B:BA:F2:7B"
fingerprint-sha256: "E5:DC:0F:4C:33:57:AD:9B:A8:23:DD:8A:CB:28:05:FC:26:0D:1B:03:07:90:80:7E:51:C0:F1:26:30:FE:46:A2"
fingerprint-im-sha1: "13:8F:CA:5A:62:16:B9:6D:5D:C0:31:1C:08:BF:2C:B9:48:36:4C:A6"
fingerprint-im-sha256: "FD:61:87:2B:D7:8E:71:0C:ED:AF:23:29:BE:20:DE:E7:F8:C7:F9:6F:B9:3D:08:4B:DC:46:8B:D5:08:76:83:94"
fingerprint-conference-sha1: "13:8F:CA:5A:62:16:B9:6D:5D:C0:31:1C:08:BF:2C:B9:48:36:4C:A6"
fingerprint-conference-sha256: "FD:61:87:2B:D7:8E:71:0C:ED:AF:23:29:BE:20:DE:E7:F8:C7:F9:6F:B9:3D:08:4B:DC:46:8B:D5:08:76:83:94"
fingerprint-proxy-sha1: "13:8F:CA:5A:62:16:B9:6D:5D:C0:31:1C:08:BF:2C:B9:48:36:4C:A6"
fingerprint-proxy-sha256: "FD:61:87:2B:D7:8E:71:0C:ED:AF:23:29:BE:20:DE:E7:F8:C7:F9:6F:B9:3D:08:4B:DC:46:8B:D5:08:76:83:94"
fingerprint-upload-sha1: "13:8F:CA:5A:62:16:B9:6D:5D:C0:31:1C:08:BF:2C:B9:48:36:4C:A6"
fingerprint-upload-sha256: "FD:61:87:2B:D7:8E:71:0C:ED:AF:23:29:BE:20:DE:E7:F8:C7:F9:6F:B9:3D:08:4B:DC:46:8B:D5:08:76:83:94"

xep-0045: 1
xep-0065: 1
xep-0115: 1
xep-0160: 1
xep-0163: 1
xep-0191: 1
xep-0198: 1
xep-0280: 1
xep-0313: 1
xep-0352: 1
xep-0357: 1
xep-0363: 1
xep-0368: 1
xep-0384: 1
xep-0398: 1

# Analytics settings
#google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

include:
- .well-known/host-meta

exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
- css/syntax.less
- css/site.less
- css/small.less

plugins:
- jekyll-sitemap
  #- jekyll-press

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
