###########################################################################
# XMPP Site Configuration

title: "mattrude.com Communication Service"
description: ""
url: "https://im.mattrude.com"
name: "mattrude.com"
baseurl: "im.mattrude.com"
destination: "/var/www/im.mattrude.com"

owner-name: "Matt Rude"
owner-pgpkey: "0xc4909ee495b0761f"
owner-url: "https://mattrude.com/"
owner-xmpp: "matt@mattrude.com"
#owner-email: "matt@mattrude.com"
owner-twitter: "mdrude"
owner-github: "mattrude"

xmpp-url: "mattrude.com" # The XMPP domain url
xmpp-host: "im.mattrude.com" # The hostname of the server
xmpp-conference-url: "conference.mattrude.com" # Multi-User Chat xep-0045
xmpp-proxy-url: "proxy.mattrude.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)
xmpp-upload-url: "upload.mattrude.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)

server-features: 1
user-guide: 0

###########################################################################
# The below values should auto update

ejabberd-version: "18.09.35"
ejabberd-gitversion: "9f7d3520aad34d5152f63135f805c874ca7d5d87"
ejabberd-upload-days: "1825"
ejabberd-upload-fsize: "1 GB"

fingerprints: 1
fingerprint-expires: "Jan 16 05:00:17 2019 GMT"
fingerprint-im-expires: "Jan 21 20:33:57 2019 GMT"
fingerprint-conference-expires: "Jan 21 20:33:57 2019 GMT"
fingerprint-proxy-expires: "Jan 21 20:33:57 2019 GMT"
fingerprint-upload-expires: "Jan 21 20:33:57 2019 GMT"
fingerprint-sha1: "8B:31:11:EB:54:81:88:B6:00:56:B5:28:BE:B7:8A:78:63:12:14:D7"
fingerprint-sha256: "26:02:C0:6A:C0:D1:E8:7C:64:1A:87:1F:F2:34:52:A7:A0:F2:47:BE:17:38:49:BB:D2:E8:2D:23:CB:1E:4F:77"
fingerprint-im-sha1: "8E:5A:E4:0E:E8:14:AA:50:81:92:4A:91:95:E7:C8:2D:F6:41:CB:B2"
fingerprint-im-sha256: "02:83:59:4B:A6:A9:13:44:5D:B9:8D:2B:C0:59:2A:11:9A:78:85:A0:5C:76:76:92:07:B5:FA:29:50:C7:9A:F4"
fingerprint-conference-sha1: "8E:5A:E4:0E:E8:14:AA:50:81:92:4A:91:95:E7:C8:2D:F6:41:CB:B2"
fingerprint-conference-sha256: "02:83:59:4B:A6:A9:13:44:5D:B9:8D:2B:C0:59:2A:11:9A:78:85:A0:5C:76:76:92:07:B5:FA:29:50:C7:9A:F4"
fingerprint-proxy-sha1: "8E:5A:E4:0E:E8:14:AA:50:81:92:4A:91:95:E7:C8:2D:F6:41:CB:B2"
fingerprint-proxy-sha256: "02:83:59:4B:A6:A9:13:44:5D:B9:8D:2B:C0:59:2A:11:9A:78:85:A0:5C:76:76:92:07:B5:FA:29:50:C7:9A:F4"
fingerprint-upload-sha1: "8E:5A:E4:0E:E8:14:AA:50:81:92:4A:91:95:E7:C8:2D:F6:41:CB:B2"
fingerprint-upload-sha256: "02:83:59:4B:A6:A9:13:44:5D:B9:8D:2B:C0:59:2A:11:9A:78:85:A0:5C:76:76:92:07:B5:FA:29:50:C7:9A:F4"

xep-0045: 1
xep-0065: 1
xep-0115: 1
xep-0160: 1
xep-0163: 1
xep-0191: 1
xep-0198: 1
xep-0280: 1
xep-0313: 1
xep-0352: 1
xep-0357: 1
xep-0363: 1
xep-0368: 1
xep-0384: 1
xep-0398: 1

# Analytics settings
#google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

include:
- .well-known/host-meta

exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
- css/syntax.less
- css/site.less
- css/small.less

plugins:
- jekyll-sitemap
  #- jekyll-press

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
