# Site settings
title: soderparr.com Communication Service
email: matt@mattrude.com
description: ""
url: "https://im.soderparr.com"
name: "soderparr.com"
baseurl: "soderparr.com"
destination: "/var/www/im.soderparr.com"
ejabberd-version: "18.12.60"
ejabberd-gitversion: "1b0d481f41bdb29cc6bbaf0d410aafed5280e337"
ejabberd-upload-days: "1825"
ejabberd-upload-fsize: "1 GB"

owner-name: "Matt Rude"
owner-pgpkey: "0xc4909ee495b0761f"
owner-url: "https://mattrude.com/"
owner-xmpp: "matt@mattrude.com"
#owner-email: "matt@mattrude.com"
owner-twitter: "mdrude"
owner-github: "mattrude"

xmpp-url: "soderparr.com"  # The domain name of the XMPP service
xmpp-host: "im.soderparr.com"
xmpp-conference-url: "conference.soderparr.com" # The domain name of the conference XMPP service
xmpp-proxy-url: "proxy.soderparr.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)
xmpp-upload-url: "upload.soderparr.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)
user-guide: 0
server-features: 1

xep-0163: 1
xep-0237: 0
xep-0280: 1
xep-0191: 1
xep-0045: 1
xep-0198: 1
xep-0313: 1
xep-0352: 1
xep-0363: 1
xep-0065: 1
xep-0357: 1

fingerprints: 1
fingerprint-expires: "Feb 25 06:00:17 2019 GMT"
fingerprint-im-expires: "Mar 23 02:27:39 2019 GMT"
fingerprint-conference-expires: "Mar 23 02:27:39 2019 GMT"
fingerprint-proxy-expires: "Mar 23 02:27:39 2019 GMT"
fingerprint-upload-expires: "Mar 23 02:27:39 2019 GMT"
fingerprint-sha1: "64:3B:2C:69:C5:6F:22:B1:5B:56:BF:DF:F6:5C:00:F1:E7:3A:C1:F0"
fingerprint-sha256: "65:50:10:9F:EC:D7:D3:A2:B2:5D:4A:7F:30:DA:98:EB:76:05:60:45:B6:BC:A4:2B:44:A6:A5:D5:F7:96:C4:74"
fingerprint-im-sha1: "1F:25:71:91:A9:25:75:69:FC:BC:2D:93:CB:C4:A3:02:BB:35:C8:AF"
fingerprint-im-sha256: "F2:1B:26:66:9D:94:35:57:B9:74:3C:CD:53:08:D5:00:60:37:8A:0E:66:7A:A2:15:7D:F6:D7:2C:7B:A7:B5:98"
fingerprint-conference-sha1: "1F:25:71:91:A9:25:75:69:FC:BC:2D:93:CB:C4:A3:02:BB:35:C8:AF"
fingerprint-conference-sha256: "F2:1B:26:66:9D:94:35:57:B9:74:3C:CD:53:08:D5:00:60:37:8A:0E:66:7A:A2:15:7D:F6:D7:2C:7B:A7:B5:98"
fingerprint-proxy-sha1: "1F:25:71:91:A9:25:75:69:FC:BC:2D:93:CB:C4:A3:02:BB:35:C8:AF"
fingerprint-proxy-sha256: "F2:1B:26:66:9D:94:35:57:B9:74:3C:CD:53:08:D5:00:60:37:8A:0E:66:7A:A2:15:7D:F6:D7:2C:7B:A7:B5:98"
fingerprint-upload-sha1: "1F:25:71:91:A9:25:75:69:FC:BC:2D:93:CB:C4:A3:02:BB:35:C8:AF"
fingerprint-upload-sha256: "F2:1B:26:66:9D:94:35:57:B9:74:3C:CD:53:08:D5:00:60:37:8A:0E:66:7A:A2:15:7D:F6:D7:2C:7B:A7:B5:98"

# Analytics settings
#google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

include: [".well-known"]
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- css/syntax.less
- css/site.less
- css/small.less

gems:
- jekyll-sitemap
#- jekyll-press

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
